### PR TITLE
update oembed to use v4 embed [APP-3850]

### PR DESCRIPTION
**Pull request by StarkMike**
New Update

### CODE REVIEW

**Review by alexpennells — APPROVED** [review]

**Review by Acezhangloo — APPROVED** [review]
LGTM

**Comment by StarkMike** [comment]
@alexpennells how do we publish this?

**Comment by alexpennells** [comment]
I don't believe we're approved by Wordpress, so I think it's just updating the link on the knowledge-base. Not sure who manages that
https://knowledge.vidyard.com/hc/en-us/articles/360009993593-Using-the-Vidyard-for-WordPress-oEmbed-plugin

**Comment by bpodrisc** [comment]
Package updated in doc 👍

**Pull request merged**
